### ISSUE TITLE
dude http://www.songspk.cloud/ now restricted  😜 

### ISSUE THREAD

**Issue by MirzaAhmedBaig** [amanvishnani/SongsPk-MusicScrapper#1]
replace url = 'http://www.songspk.cloud/indian_movie/'+page+'_List.html' by url = 'http://songspk3.club/songs-movies-'+page+'.html' 😜

**Comment by MirzaAhmedBaig** [comment]
no this is also not working

**Comment by MirzaAhmedBaig** [comment]
url = 'http://www.songspk.pub/indian_movie/'+page+'_List.html'
this one is working

**Comment by amanvishnani** [comment]
Commit #1247025 fixes this issue.
Thank You for reporting.
